version: '3'

networks:
  backend:
    driver: bridge

services:

  nginx:
    container_name: "${APP_NAME}_nginx"
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/${APP_NAME}"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_ROOT="/var/www/${APP_NAME}/public"
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && envsubst '$$NGINX_ROOT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
    networks:
      - backend

  php:
    container_name: "${APP_NAME}_php"
    image: php:${PHP_VERSION}-fpm
    working_dir: /var/www/${APP_NAME}
    volumes:
      - "./:/var/www/${APP_NAME}"
    networks:
      - backend